### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by ThIsLinked** [jamal2362/Styx#103]
Hi again. If you do not mind, then I will be the representative of Styx on the Russian forum. And with regards to him. There people have complaints about the icon. They say that the blue globe looks somehow strange against this background. Maybe you should think about it?

**Comment by ThIsLinked** [comment]
By the way, can you put me on the list of authors?  I also want to contribute to the improvement of the browser. True, I have no experience in Kotlin, but I will help you with something else. If you agree, then write me your contact (Telegram or Viber), so that I can quickly contact you in case of questions. Thanks.

**Comment by jamal2362** [comment]
Hello,
I don't know exactly what you mean but the background matches the logo. To give the background a different color I don't think it makes sense because it doesn't look good.

Unless you have the matching color code then I can take a look at this. But the logo stays as it is, that's what makes Styx stand out.

![23235019](https://user-images.githubusercontent.com/15986930/140635890-06449794-6526-4fe5-92cf-2e405cabf628.png)

**Comment by jamal2362** [comment]
Currently, no change in the logo is considered.
Therefore I close here.
