### ISSUE TITLE
The proxy configuration option is gone?

### ISSUE THREAD

**Issue by issu-shooter** [jamal2362/Styx#37]
When I first used styx, it just has the thing I needed most: i2p proxy support, but after a few updates from f-droid I can no longer find the Proxy configuration option... Is it a bug or styx no longer supports custom proxy?

**Comment by jamal2362** [comment]
Styx no longer support proxy connections.

See here:
https://github.com/jamal2362/Styx/issues/20

**Comment by Slion** [comment]
@issu-shooter It should still be in Fulguris which the browser Styx is based on.
If it was working for you with Styx before it should still work in Fulguris.
https://slions.net/resources/fulguris.10/

**Comment by jamal2362** [comment]
The only thing that worked was I2P but e.g. Orbot did not.

I don't recommend using a proxy in a browser because the identity may be revealed.

If you want to use Orbot/Tor or I2P then you can download the respective app from the Play Store.

I can't guarantee the security about proxy in Styx + the whole thing was very outdated/defective.
